version: '3'

services:
  user-simulator: 
    build: user-simulator
    env_file: user-simulator/.env
    depends_on:
      - api-server
      - log-shipper
    networks:
      - aparnet
    logging:
      driver: fluentd
      options:
        # fluentd-address: # default localhost:24224
        tag: docker.{{.ID}} # container-id by default
        # fluentd-sub-second-precision: "true"
    
  api-server:
    build: api-server
    env_file: api-server/.env
    networks:
      - aparnet
    logging:
      driver: fluentd
    depends_on:
      - log-shipper
  
  log-shipper:
    build: log-shipper
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    env_file: log-shipper/.env

networks:
  aparnet: